### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by midd33** [bocadillodeatun/proxpn_python_client#1]
I'm getting this when I try to execute the script using python proxpn.py

Traceback (most recent call last):
  File "proxpn.py", line 80, in <module>
    import urllib.request
ImportError: No module named request

**Comment by bocadillodeatun** [comment]
Sorry for the (very) late reply :)

This script depends on the "python-urllib3" package, thus you first need to install it in order for this script to run.

I have just modified the script to detect this circumstance and print the following message when this happens:
```
ERROR: This script depends on the 'python-urllib3', and it looks like you don't have it installed.
       Fortunately, this is easy to fix. Just install that package using your distro's package
       manager and re-run this script.
       Examples:

       - Archlinux:     sudo pacman -S python-urllib3
       - Ubuntu/Debian: sudo apt-get install python-urllib3
       - Redhat/Fedora: sudo yum install python-urllib3
       - OpenSuse:      sudo yast2 --install python-urllib3
       - Etc..
```

Hope this helps :)
